var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(){ovi.provide("nokia.maps.routing.WaypointParameterList");
nokia.maps.routing.WaypointParameterList=new ovi.Class({initialize:function(){this.coords=[];this.places=[];this.locations=[];this.waypointList=[]},addCoordinate:function(f){this.waypointList.push(f);this.coords.push(f)},addPlace:function(f){this.waypointList.push(f);this.places.push(f)},addLocation:function(f){this.waypointList.push(f);this.locations.push(f)},size:function(){return this.waypointList.length||this.coords.length+this.places.length+this.locations.length},clear:function(){this.coords=
[];this.places=[];this.locations=[];this.waypointList=[]},toCoordinates:function(){var f=[],e,c,b;e=0;for(c=this.waypointList.length;e<c;e++)b=this.waypointList[e],"latitude"in b&&"longitude"in b?this.Zs(b,f):"locations"in b?this.bt(b,f):("displayPosition"in b||"navigationPosition"in b)&&this.Nm(b,f);this.waypointList.length==0&&(this.$s(f),this.ct(f),this.at(f));return f},Zs:function(f,e){e.push(f)},bt:function(f,e){for(var c=0,b=f.locations.length;c<b;c++)this.Nm(f.locations[c],e)},Nm:function(f,
e){f.displayPosition?e.push(f.displayPosition):f.navigationPosition&&e.push(f.navigationPosition)},$s:function(f){for(var e=0,c=this.coords.length;e<c;e++)f.push(this.coords[e])},ct:function(f){for(var e=0,c=this.places.length;e<c;e++)this.Nm(f,this.places[e].locations)},at:function(f,e){var e=e||this.locations,c,b,a;b=0;for(a=this.locations.length;b<a;b++)c=e[b],c.displayPosition?f.push(c.displayPosition):c.navigationPosition&&f.push(c.navigationPosition)}});ovi.provide("nokia.maps.routing.component.RouteResultSet");
(function(f){var e=f.map;f.routing.component.RouteResultSet=new ovi.Class({initialize:function(c,b){var a=this.container=new e.Container,g=b||{},d=c.waypoints,i=c.mode.transportModes,j;j=c.shape;var h,m,l=e.StandardMarker;m=e.Polyline;h=g.width||5;g=g.color||"#00F8";j&&(m=new m(j,{pen:new f.util.Pen({lineWidth:h,strokeColor:g,lineJoin:"round"})}),a.objects.add(m));if(d){j=d.length;m=i==="walk"?d[0].originalPosition:d[0].mappedPosition;m=new l(m,{text:"A",identifier:"waypoints"});a.objects.add(m);
for(h=1;h<j-1;h++)m=i==="walk"?d[h].originalPosition:d[h].mappedPosition,m=new l(m,{text:"",identifier:"waypoints",pos:h-1}),a.objects.add(m);m=i==="walk"?d[j-1].originalPosition:d[j-1].mappedPosition;m=new l(m,{text:"B",identifier:"waypoints"});a.objects.add(m)}},container:null})})(nokia.maps);ovi.provide("nokia.maps.routing.Maneuver");ovi.provide("nokia.maps.routing.Mode");ovi.provide("nokia.maps.routing.Route");ovi.provide("nokia.maps.routing.RouteLeg");ovi.provide("nokia.maps.routing.RouteSegment");
ovi.provide("nokia.maps.routing.RouteSummary");ovi.provide("nokia.maps.routing.ServiceError");ovi.provide("nokia.maps.routing.Waypoint");ovi.provide("nokia.maps.routing.nokia.HexWriter");(function(){var f=nokia.maps.routing.nokia.HexWriter=function(){this.oe=[]};ovi.extend(f.prototype,{write:function(e){e=e.toString(16);this.oe.push(e.length<2?"0"+e:e)},getContent:function(){return this.oe.join("")}})})();ovi.provide("nokia.maps.routing.nokia.ArrayReader");
(function(f){f.ArrayReader=function(e){this.bo=e;this.Wo=this.bo.length;this.ga=0};f.ArrayReader.prototype.read=function(){if(this.ga>=this.Wo)return-1;return this.bo[this.ga++]}})(nokia.maps.routing.nokia);ovi.provide("nokia.maps.routing.nokia.ArrayWriter");(function(){var f=nokia.maps.routing.nokia.ArrayWriter=function(){this.oe=[]};ovi.extend(f.prototype,{write:function(e){this.oe.push(e)},getContent:function(){return this.oe}})})();ovi.provide("nokia.maps.routing.nokia.TLVTag");
(function(f){f.TLVTag=Function();f.TLVTag.prototype.toString=function(){return this.od}})(nokia.maps.routing.nokia);ovi.provide("nokia.maps.routing.nokia.HexReader");
(function(){var f={48:0,49:1,50:2,51:3,52:4,53:5,54:6,55:7,56:8,57:9,97:10,65:10,98:11,66:11,99:12,67:12,100:13,68:13,101:14,69:14,102:15,70:15},e=nokia.maps.routing.nokia.HexReader=function(c){this.ga=0;this.oe=c;this.Wo=c.length};ovi.extend(e.prototype,{Ip:function(){for(var c,b,a=1,e=this.oe,d=this.ga;(c=e.charCodeAt(d++))&&(a=(b=f[c])===void 0););this.ga=d;return a?-1:b},read:function(){var c=this.Ip(),b=this.Ip();return c<0||b<0?-1:c*16+b}})})();ovi.provide("nokia.maps.routing.nokia.Maneuver");
(function(f){function e(a,b,d,e){var f="",h=0,m=ovi.Array(),d=d||"",e=e||c;ovi.Array.forEach(a,function(a){var g;a=a.split(":");m.push(h=a.length===2?+a[1]:h);g=((a=a[0]).indexOf("_")?d:f)+a,a=g;e(h++,a,b);f=a.substr(0,a.lastIndexOf("_"))});if(d)b["_constVals"+d]=m,b.Au=function(a,b){var c=this["_constVals"+a];return c&&c.indexOf(b)!==-1}}function c(a,b,c){c[b]=a}var b=new ovi.Class({initialize:function(){this.trafficDirection=this.TRAFFIC_DIR_RIGHT;this.command=this.nextStreetName=this.streetName=
this.routeName=this.signPost="";this.mapOrientation=this.angle=0;this.action=this.ACTION_UNDEFINED;this.turn=this.TURN_UNDEFINED;this.distanceFromStart=this.distanceFromPreviousManeuver=0},getIcon:function(){var a=this.ICON_UNDEFINED;if(this.trafficDirection===this.TRAFFIC_DIR_RIGHT){switch(this.lu){case this.ACTION_UNDEFINED:a=this.ICON_UNDEFINED;break;case this.ACTION_NO_ACTION:a=this.ICON_GO_STRAIGHT;break;case this.ACTION_END:a=this.ICON_END;break;case this.ACTION_STOPOVER:a=this.ICON_UNDEFINED;
break;case this.ACTION_JUNCTION:a=this.ICON_UNDEFINED;break;case this.ACTION_ROUNDABOUT:a=this.ICON_UNDEFINED;break;case this.ACTION_UTURN:a=this.ICON_UTURN_LEFT;break;case this.ACTION_ENTER_HIGHWAY_FROM_RIGHT:a=this.ICON_ENTER_MOTORWAY_LEFT_LANE;break;case this.ACTION_ENTER_HIGHWAY_FROM_LEFT:a=this.ICON_ENTER_MOTORWAY_RIGHT_LANE;break;case this.ACTION_ENTER_HIGHWAY:a=this.ICON_ENTER_MOTORWAY_LEFT_LANE;break;case this.ACTION_LEAVE_HIGHWAY:a=this.ICON_ENTER_MOTORWAY_RIGHT_LANE;break;case this.ACTION_CHANGE_HIGHWAY:a=
this.ICON_UNDEFINED;break;case this.ACTION_CONTINUE_HIGHWAY:a=this.ICON_GO_STRAIGHT;break;case this.ACTION_FERRY:a=this.ICON_FERRY;break;case this.ACTION_PASS_JUNCTION:a=this.ICON_GO_STRAIGHT;break;case this.ACTION_PASS_STATION:a=this.ICON_GO_STRAIGHT}switch(this.turn){case this.TURN_KEEP_MIDDLE:a=this.ICON_GO_STRAIGHT;break;case this.TURN_KEEP_RIGHT:a=this.ICON_KEEP_RIGHT;break;case this.TURN_LIGHT_RIGHT:a=this.ICON_LIGHT_RIGHT;break;case this.TURN_QUITE_RIGHT:a=this.ICON_QUITE_RIGHT;break;case this.TURN_HEAVY_RIGHT:a=
this.ICON_HEAVY_RIGHT;break;case this.TURN_KEEP_LEFT:a=this.ICON_KEEP_LEFT;break;case this.TURN_LIGHT_LEFT:a=this.ICON_LIGHT_LEFT;break;case this.TURN_QUITE_LEFT:a=this.ICON_QUITE_LEFT;break;case this.TURN_HEAVY_LEFT:a=this.ICON_HEAVY_LEFT;break;case this.TURN_ROUNDABOUT_1:a=this.ICON_ROUNDABOUT_1;break;case this.TURN_ROUNDABOUT_2:a=this.ICON_ROUNDABOUT_2;break;case this.TURN_ROUNDABOUT_3:a=this.ICON_ROUNDABOUT_3;break;case this.TURN_ROUNDABOUT_4:a=this.ICON_ROUNDABOUT_4;break;case this.TURN_ROUNDABOUT_5:a=
this.ICON_ROUNDABOUT_5;break;case this.TURN_ROUNDABOUT_6:a=this.ICON_ROUNDABOUT_6;break;case this.TURN_ROUNDABOUT_7:a=this.ICON_ROUNDABOUT_7;break;case this.TURN_ROUNDABOUT_8:a=this.ICON_ROUNDABOUT_8;break;case this.TURN_ROUNDABOUT_9:a=this.ICON_ROUNDABOUT_9;break;case this.TURN_ROUNDABOUT_10:a=this.ICON_ROUNDABOUT_10;break;case this.TURN_ROUNDABOUT_11:a=this.ICON_ROUNDABOUT_11;break;case this.TURN_ROUNDABOUT_12:a=this.ICON_ROUNDABOUT_12}}else{switch(this.action){case this.ACTION_UNDEFINED:a=this.ICON_UNDEFINED;
break;case this.ACTION_NO_ACTION:a=this.ICON_GO_STRAIGHT;break;case this.ACTION_END:a=this.ICON_END;break;case this.ACTION_STOPOVER:a=this.ICON_UNDEFINED;break;case this.ACTION_JUNCTION:a=this.ICON_UNDEFINED;break;case this.ACTION_ROUNDABOUT:a=this.ICON_UNDEFINED;break;case this.ACTION_UTURN:a=this.ICON_UTURN_RIGHT;break;case this.ACTION_ENTER_HIGHWAY_FROM_RIGHT:a=this.ICON_ENTER_MOTORWAY_LEFT_LANE;break;case this.ACTION_ENTER_HIGHWAY_FROM_LEFT:a=this.ICON_ENTER_MOTORWAY_RIGHT_LANE;break;case this.ACTION_ENTER_HIGHWAY:a=
this.ICON_ENTER_MOTORWAY_RIGHT_LANE;break;case this.ACTION_LEAVE_HIGHWAY:a=this.ICON_ENTER_MOTORWAY_LEFT_LANE;break;case this.ACTION_CHANGE_HIGHWAY:a=this.ICON_UNDEFINED;break;case this.ACTION_CONTINUE_HIGHWAY:a=this.ICON_GO_STRAIGHT;break;case this.ACTION_FERRY:a=this.ICON_FERRY;break;case this.ACTION_PASS_JUNCTION:a=this.ICON_GO_STRAIGHT;break;case this.ACTION_PASS_STATION:a=this.ICON_GO_STRAIGHT}switch(this.turn){case this.TURN_KEEP_MIDDLE:a=this.ICON_GO_STRAIGHT;break;case this.TURN_KEEP_RIGHT:a=
this.ICON_KEEP_RIGHT;break;case this.TURN_LIGHT_RIGHT:a=this.ICON_LIGHT_RIGHT;break;case this.TURN_QUITE_RIGHT:a=this.ICON_QUITE_RIGHT;break;case this.TURN_HEAVY_RIGHT:a=this.ICON_HEAVY_RIGHT;break;case this.TURN_KEEP_LEFT:a=this.ICON_KEEP_LEFT;break;case this.TURN_LIGHT_LEFT:a=this.ICON_LIGHT_LEFT;break;case this.TURN_QUITE_LEFT:a=this.ICON_QUITE_LEFT;break;case this.TURN_HEAVY_LEFT:a=this.ICON_HEAVY_LEFT;break;case this.TURN_ROUNDABOUT_1:a=this.ICON_ROUNDABOUT_1_LH;break;case this.TURN_ROUNDABOUT_2:a=
this.ICON_ROUNDABOUT_2_LH;break;case this.TURN_ROUNDABOUT_3:a=this.ICON_ROUNDABOUT_3_LH;break;case this.TURN_ROUNDABOUT_4:a=this.ICON_ROUNDABOUT_4_LH;break;case this.TURN_ROUNDABOUT_5:a=this.ICON_ROUNDABOUT_5_LH;break;case this.TURN_ROUNDABOUT_6:a=this.ICON_ROUNDABOUT_6_LH;break;case this.TURN_ROUNDABOUT_7:a=this.ICON_ROUNDABOUT_7_LH;break;case this.TURN_ROUNDABOUT_8:a=this.ICON_ROUNDABOUT_8_LH;break;case this.TURN_ROUNDABOUT_9:a=this.ICON_ROUNDABOUT_9_LH;break;case this.TURN_ROUNDABOUT_10:a=this.ICON_ROUNDABOUT_10_LH;
break;case this.TURN_ROUNDABOUT_11:a=this.ICON_ROUNDABOUT_11_LH;break;case this.TURN_ROUNDABOUT_12:a=this.ICON_ROUNDABOUT_12_LH}}return a}});f.Maneuver=b;f=f.Maneuver.prototype;e("UNDEFINED NO_ACTION END STOPOVER JUNCTION ROUNDABOUT UTURN ENTER_HIGHWAY_FROM_RIGHT _LEFT ENTER_HIGHWAY LEAVE_HIGHWAY CHANGE_HIGHWAY CONTINUE_HIGHWAY FERRY PASS_JUNCTION _STATION".split(" "),f,"ACTION_");e("UNDEFINED NO_TURN KEEP_MIDDLE _RIGHT LIGHT_RIGHT QUITE_RIGHT HEAVY_RIGHT KEEP_LEFT LIGHT_LEFT QUITE_LEFT HEAVY_LEFT RETURN ROUNDABOUT_1 _2 _3 _4 _5 _6 _7 _8 _9 _10 _11 _12".split(" "),
f,"TURN_");e("UNDEFINED GO_STRAIGHT UTURN_RIGHT _LEFT KEEP_RIGHT LIGHT_RIGHT QUITE_RIGHT HEAVY_RIGHT KEEP_LEFT LIGHT_LEFT QUITE_LEFT HEAVY_LEFT ENTER_MOTORWAY_RIGHT_LANE _LEFT_LANE LEAVE_MOTORWAY_RIGHT_LANE _LEFT_LANE MOTORWAY_KEEP_RIGHT _LEFT ROUNDABOUT_1 _2 _3 _4 _5 _6 _7 _8 _9 _10 _11 _12 _1_LH _2_LH _3_LH _4_LH _5_LH _6_LH _7_LH _8_LH _9_LH _10_LH _11_LH _12_LH END FERRY".split(" "),f,"ICON_",function(a,b,c){b=b.replace(/(_\d+)+(_\d+)/g,"$2");c[b]=a})})(nokia.maps.routing.nokia);ovi.provide("nokia.maps.routing.nokia.ioc.Definition");
(function(f){var e=f.util.f;f.routing.nokia.ioc.Definition=new ovi.Class({initialize:function(c){typeof c.type!=="string"&&e("Missing object type for id "+c.id);this.id=this.st(c.id,c.type);this.type=c.type;this.scope=c.scope;this.autowire=c.autowire;this.properties=c.properties},st:function(c,b){if(c)return this.Yq(c),c;var a=this.tt(b);return a.charAt(0).toLowerCase()+a.substring(1)},Yq:function(c){c.indexOf(".")!==-1&&e("An object's id cannot contain dots, id "+c)},tt:function(c){return c.substring(c.lastIndexOf(".")+
1)}})})(nokia.maps);ovi.provide("nokia.maps.routing.nokia.Options");
nokia.maps.routing.nokia.Options={TRANSPORT_MODE:{car:0,pedestrian:2,bicycle:6,publicTransport:4,truck:5},ROUTE_TYPE:{fastest:0,shortest:1,economic:1024,directDrive:0,scenic:1,pedestrian:0},Aq:{avoidTollroad:"allowTollRoads",avoidMotoway:"allowHighways",avoidTunnel:"allowTunnel",avoidDirtRoad:"allowDirtRoads",avoidRailFerry:"allowRailFerries",avoidBoatFerry:"allowFerries"},ROUTE_OPTIONS:{allowHighways:!0,allowTunnels:!0,allowFerries:!0,allowTollRoads:!0,allowDirtRoads:!0,allowRailFerries:!0},routeType:0,
routeMode:0,setOptionsFromMode:function(f){this.routeMode=this.TRANSPORT_MODE[f.transportModes];this.routeType=this.ROUTE_TYPE[f.type];var f=f.options.split(","),e;for(e in f)this.ROUTE_OPTIONS[this.Aq[f[e]]]=!1},getOptions:function(){var f=this.ROUTE_OPTIONS;return{routeType:this.routeType,routeMode:this.routeMode,allowHighways:f.allowHighways,allowTunnels:f.allowTunnels,allowFerries:f.allowFerries,allowTollRoads:f.allowTollRoads,allowDirtRoads:f.allowDirtRoads,allowRailFerries:f.allowRailFerries}}};
ovi.provide("nokia.maps.routing.component.RouteComponent");
(function(f){var e=f.map;f.routing.component.RouteComponent=new ovi.Class({Extends:e.component.Component,initialize:function(c,b,a){this.ek=b||new nokia.maps.search.Manager;this.mk=new nokia.maps.search.Manager;this.Wi=new nokia.maps.search.Manager;this.Hd=c||new nokia.maps.routing.Manager;this.Hd.addObserver("state",this.qp,this);this.ek.addObserver("state",this.zp,this);this.mk.addObserver("state",this.pp,this);this.Wi.addObserver("state",this.op,this);this.O=[];this.pa=this.za=0;this.startLocation=
this.destinationLocation=null;this.Yf=[];this.ye=[];this.zo=!1;this.qh=a||[{type:"shortest",transportModes:["car"],options:""}]},destroy:function(){this.Hd.removeObserver("state",this.qp,this);this.ek.removeObserver("state",this.zp,this);this.mk.removeObserver("state",this.pp,this);this.Wi.removeObserver("state",this.op,this);this.Hd.destroy();this._super()},d:"Route",A:"0.0.0.1",attach:function(c){this._super(c);if(c=c.getComponentById("RouteView"))if(c.useRouteComponent(this),c=c.getMode().transportModes)this.qh[0].transportModes=
c},detach:function(c){this.searches&&this.searches.Ht&&this.searches.Ht(!0);this._super(c)},startRouting:function(c,b,a,e,d,f){if(!this.Zd&&c&&b){this.Zd=!0;this.O=[];this.Yf=[];this.Zm();this.pa=this.za=0;a.unshift(c);a.push(b);this.ye=a;this.Gl=0;if(c=this.ye.shift())this.ek.search(c),this.Hl=!0;else return this.Zd=!1;this.qh=[{type:e,transportModes:d,options:f,trafficMode:this.qh.traficMode}]}},calculateRoute:function(c){var b;if(this.pa&&this.za&&this.hj(this.Yf,null)==-1)this.Zd=!0,b=new nokia.maps.routing.WaypointParameterList,
b.coords=this.O,this.Hd.calculateRoute(b,[].concat(c||this.qh))},zp:function(c){if(this.Hl&&(this.Hl=!1,c.state=="finished")){c=c.locations;c.length?this.Gl?this.ye.length?(this.insertViaCoord(c[0].displayPosition),this.Yf.push(c[0])):(this.Up(c[0].displayPosition,!1),this.set("destinationLocation",c[0])):(this.Yp(c[0].displayPosition,!1),this.set("startLocation",c[0])):(this.Zd=!1,this.Gl?this.ye.length?this.Yf.push(null):this.set("destinationLocation",null):this.set("startLocation",null));if(this.ye.length)if(c=
this.ye.shift())this.ek.search(c),this.Hl=!0;else return this.clear();else this.calculateRoute();this.Gl++}},ye:null,qh:null,Ie:null,qp:function(c){var b=this.Ie;if(c.state!="finished"||!this.Zd){if(c.state=="failed")this.Zd=!1,b&&b.objects.getLength()&&b.objects.get(0).constructor==e.Polyline&&b.objects.removeAt(0),c.clear()}else b=c.routes,this.searches&&this.searches.showRouteDescription(b[0]),this.mapDisplay&&!this.zo&&this.Jt(b[0]),this.Zd=!1,c.clear()},Jt:function(c){this.Zm();if(c&&c.shape)c=
(new nokia.maps.routing.component.RouteResultSet(c)).container,this.Dr(c),this.mapDisplay.objects.add(c),this.mapDisplay.zoomTo(c.getBoundingBox()),this.Ie=c},Zm:function(){if(this.Ie)this.mapDisplay.objects.remove(this.Ie),this.Ie=null;this.Fb&&this.Fb.objects.clear()},clear:function(){this.O=[];this.pa=this.za=0;this.Zm();this.Hd.clear();this.Zd=!1},clearRouteLine:function(){var c=this.Ie;c&&c.objects.remove(c.objects.get(0))},zoomToManeuver:function(c){this.mapDisplay.setCenter(c.position,"default")},
disableRoutePainting:function(){this.zo=!0},getWaypointCoords:function(){return[].concat(this.O)},Yp:function(c,b){this.pa?(this.jm(this.O[0],c),this.O[0]=c):(this.O.unshift(c),this.Mk(c,"A"));b&&this.mk.reverseGeocode(c);this.pa=1;return c},setStart:function(c){return this.Yp(c,!0)},Up:function(c,b){var a=this.O.length-1;this.za?(this.jm(this.O[a],c),this.O[a]=c):(this.O.push(c),this.Mk(c,"B"));b&&this.Wi.reverseGeocode(c);this.za=1;return c},setDestination:function(c){return this.Up(c,!0)},pp:function(c){this.np(c,
"start")},op:function(c){this.np(c,"destination")},np:function(c,b){c.state=="finished"&&this.set(b+"Location",c.locations[0])},insertViaCoord:function(c,b){this.hj(this.O,c)!==-1&&ovi.error("Specified coordinate already was added.");this.za&&!this.pa&&b===void 0&&(b=0);b!==void 0?this.O.splice(b+this.pa,0,c):this.O.splice(this.O.length-this.za,0,c);this.Mk(c,"");return c},setViaCoord:function(c,b){var a=this.hj(this.O,c),e=b+this.pa;b+this.pa+this.destinationSet>=this.O.length&&ovi.error("No ViaCoord Specified at the given position.");
a!==-1&&a!=b&&ovi.error("Specified coordinate already was added.");this.jm(this.O[e],c);return this.O[e]=c},jm:function(c,b){var a;if(a=c.ce)delete c.ce,a.set("coordinate",b),b.ce=a,a.Cm=b},removeWaypointCoord:function(c){var b=this.hj(this.O,c),a=this.Ie,f=this.O.length-this.pa-this.za;if(!b&&this.pa){if(!this.za&&f)return ovi.error("Start coord may not be removed in that state");f?(this.set("startLocation",this.Yf.shift()),this.mk.reverseGeocode(this.O[1])):(this.set("startLocation",null),this.za&&
a.objects.get(0).constructor==e.Polyline&&a.objects.removeAt(0),a&&a.objects.getLength()?a.objects.removeAt(0):this.Fb&&this.Fb.objects.getLength()&&this.Fb.objects.removeAt(0),this.pa=0)}else if(b==this.O.length-1&&this.za){if(!this.pa&&f)return ovi.error("Destination coord may not be removed in that state");f?(this.set("destinationLocation",this.Yf.pop()),this.Wi.reverseGeocode(this.O[b-1])):(this.set("destinationLocation",null),this.pa&&a.objects.get(0).constructor==e.Polyline&&a.objects.removeAt(0),
a&&a.objects.getLength()?a.objects.removeAt(a.objects.getLength()-1):this.Fb&&this.Fb.objects.getLength()&&this.Fb.objects.removeAt(this.Fb.objects.getLength()-1),this.za=0)}this.O.splice(b,1);c.ce&&this.Fb.objects.indexOf(c.ce)&&this.Fb.objects.remove(c.ce);delete c.ce},Dr:function(c){var b=this.O.length,a,e;for(a=0;a<b;a++)e=c.objects.get(a+1),e.Cm=this.O[a],this.O[a].ce=e},Mk:function(c,b){if(!this.Fb)this.mapDisplay.objects.add(this.Fb=new e.Container);this.Fb.objects.add(c.ce=new e.StandardMarker(c,
{text:b,identifier:"waypoints",Cm:c}))},hj:function(c,b){if(Array.indexOf)return c.indexOf(b);else{for(var a=0,e=c.length;a<e;a++)if(c[a]===b)return a;return-1}}})})(nokia.maps);ovi.provide("nokia.maps.routing.component.RightClick");
(function(f){var e=f.routing.component;e.RightClick=new ovi.Class({Extends:f.map.component.Component,Su:[],Aa:[],d:"routing.component.RightClick",A:"0.0.0.1",initialize:function(c,b,a){this.Hd=c;this.Sd=!!a},attach:function(c){var b=new nokia.maps.search.Manager,a=c.getComponentById("RightClick");this._super(c);this.Hd=this.Hd||new f.routing.Manager;this.L=c.getComponentById("Route");if(!this.L)c.components.add(this.L=new e.RouteComponent(this.Hd,b));a&&(a.useRouteComponent(this),a.fixDestinationWaypoint(this.Sd))},
detach:function(c){var b=c.getComponentById("RightClick");b&&b.useRouteComponent(null);this._super(c)},setWaypoints:function(c,b){var a=this.L;switch(c){case "start":a.setStart(b);break;case "via":a.insertViaCoord(b);break;case "dest":this.Sd||a.setDestination(b)}this.calculateRoute()},removeWaypoint:function(c){this.L.removeWaypointCoord(c.Cm);this.L.calculateRoute()},calculateRoute:function(){this.L.calculateRoute()}})})(nokia.maps);ovi.provide("nokia.maps.routing.Manager");
(function(f){var e=f.routing.Manager=new ovi.Class({Extends:f.util.OObject,initialize:function(c,b){var a=c||{};this.Dc=b||new f.Config;if(this.constructor===e)return new e.Va(a);this._super(a)},destroy:function(){this.Va=null},Statics:{setDefImpl:function(c){return this.Va||(this.Va=c),!1}}})})(nokia.maps);ovi.provide("nokia.maps.routing.nokia.ioc.Injector");
(function(f){var e=f.util;f.routing.nokia.ioc.Injector=new ovi.Class({Statics:{ID:"injector",Scope:{None:0,Singleton:1},InjectorInitializationError:"InjectorInitializationError"},initialize:function(c){this.bs(c.definitions||{});this.namespace=c.namespace||window;this.container={};this.initialized=!1},get:function(c){this.initialized||this.as();return this.ck(c)},addDefinition:function(c){this.initialized&&e.Za("Can't add definitions after container initialization");c=new nokia.maps.routing.nokia.ioc.Definition(c);
this.definitions[c.id]=c},isInitialized:function(){return this.initialized},bs:function(c){this.definitions={};for(var b=0,a=c.length;b<a;b++)this.addDefinition(c[b])},as:function(){for(var c in this.definitions)this.container[c]||this.Po(this.definitions[c])&&this.ck(c);this.initialized=!0},ck:function(c){if(c===this.constructor.ID)return this;if(this.container[c])return this.container[c];return this.cs(this.Ir(c))},Ir:function(c){var b=this.definitions[c];b||e.Tb(this.constructor.InjectorInitializationError,
"Missing definition with id: "+c);return b},cs:function(c){var b=c.type,a=this.Pp(this.namespace,b);typeof a!=="function"&&e.Tb(this.constructor.InjectorInitializationError,"No constructor found for type: "+b);b=new a;c.autowire?this.Nq(b):this.rt(c.id,b,c.properties);this.Po(c)&&(this.container[c.id]=b);return b},Nq:function(c){for(var b in c)typeof c[b]!=="function"&&this.hs(b)&&(c[b]=this.ck(b))},rt:function(c,b,a){for(var f in a){var d=a[f],i=typeof d==="string"?d:d.ref;i?b[f]=this.ck(i):d.value?
b[f]=d.value:e.Tb(this.constructor.InjectorInitializationError,"Neither value nor ref are set for dependency: "+c)}},Pp:function(c,b){if(b.indexOf(".")!==-1){var a=b.split(".")[0],e=b.replace(/[^.]*\.(.*)/,"$1");return this.Pp(c[a],e)}return c[b]},Po:function(c){return c.scope===this.constructor.Scope.Singleton},hs:function(c){return c===this.constructor.ID||this.definitions[c]}})})(nokia.maps);ovi.provide("nokia.maps.routing._packaging.package");ovi.provide("nokia.maps.routing.nokia.Context");
var Gb=nokia.maps.routing.nokia;Gb.Context={namespace:Gb,definitions:[{type:"Manager",autowire:!0},{type:"RouteCreator",scope:nokia.maps.routing.nokia.ioc.Injector.Scope.Singleton,autowire:!0}]};ovi.provide("nokia.maps.routing.nokia.TLVCodec");
(function(f){f.TLVCodec={$c:function(e,c,b){for(var a=0;a<c;a++)e.push((b>>>a*8)%256)},qb:function(e,c){for(var b=0,a=e.length,f=0;f<c&&f<a;f++)b+=e[f]<<f*8;return b},zq:function(e,c,b){var a=[];this.$c(a,c,b);this.xq(e,a)},Kp:function(e,c){var b=this.Wm(e,c);return b&&b.length>=c?this.qb(b,c):-1},Br:function(e,c){e.push(c==="false"?0:c?255:0)},xo:function(e){return!!e[0]},Bo:function(e,c,b){var a=c.length;if(b)this.Cr(e,c),e.push(0);else for(b=0;b<a;b++)e.push(c.charCodeAt(b)&255);e.push(0)},Ui:function(e,
c){var b,a,f,d=[],i=e.length;if(c)return this.sr(e);else{f=i>1&&e[i-1]===0&&e[i-2]===0?2:1;for(b=f===2?1:0;b<i;b+=f)a=e[b]&255,a>0&&d.push(a);return this.Kq(d)}},Cr:function(e,c){for(var b=0,a=c.length,f,d;b<a;){if(((f=c.charCodeAt(b++))&63488)===55296)throw"UTF16 encoding mismatch";f>65535&&(f-=65536,d=f>>>10&1023|55296,e.push(d|255),e.push(d>>>8|255),f=56320|f&1023);e.push(f&255);e.push(f>>>8&255)}},sr:function(e){for(var c=[],b=0,a=e.length,f,d;b<a;){f=e[b++]+e[b++]*256;if((f&63488)>=55296&&(f&
63488)<=57343){d=e[b++]+e[b++]*255;if((f&64512)!==55296||(d&64512)!==56320)throw"UTF16 decoding mismatch";f=((f&1023)<<10)+(d&1023)+65536}f>0&&c.push(String.fromCharCode(f))}return c.join("")},Kq:function(e){for(var c=[],b=0,a=e.length;b<a;)c.push(String.fromCharCode(e[b++]));return c.join("")},Pu:function(e){for(var c=[],b=0,a=e.length;b<a;)c.push(e.charCodeAt(b++));return c},xq:function(e,c){for(var b=0,a=c.length;b<a;b++)e.write(c[b])},Wm:function(e,c){for(var b=[],a,f=0;f<c;f++){a=e.read();if(a<
0)return null;b.push(a)}return b},ju:function(e,c){var b=[],a=c.Y,g=c.gb,d=g.u;this.zq(e,1,g.d);if(d<this.TYPE_BINARY&&typeof a==="object")b=a?a:[];else switch(d){case this.TYPE_VOID:break;case this.TYPE_BOOL:this.Br(b,a);break;case this.TYPE_UINT8:this.$c(b,1,a);break;case this.TYPE_UINT16:this.$c(b,2,a);break;case this.TYPE_UINT32:this.$c(b,4,a);break;case this.TYPE_UINT64:this.$c(b,8,a);break;case this.TYPE_FLOAT:this.uu(b,a);break;case this.TYPE_DOUBLE:this.tu(b,a);break;case this.TYPE_STRING:this.Bo(b,
a,!1);break;case this.TYPE_UNICODE_STRING:this.Bo(b,a,!0);break;case this.TYPE_BINARY:b=a;break;case this.TYPE_COMPLEX:b=new f.ArrayWriter;this.yq(b,a);b=b.getContent();break;case this.TYPE_CUSTOM:g.Oc&&g.Oc.call(this,b,a);break;default:throw"Unsupported type: "+d;}this.zq(e,2,b.length);this.xq(e,b)},yq:function(e,c){for(var b=0,a=c.length;b<a;b++)this.ju(e,c[b])},Jp:function(e,c){for(var b=[],a=e.read();a!==-1;a=e.read()){if(a===0){b[b.length]={gb:this.EOF,Y:null};break}var a=this.Tl["".concat(c,
" ",a)],g=this.Kp(e,2),d=g>=0?this.Wm(e,g):[],i=null;if(a){switch(a.u){case this.TYPE_VOID:break;case this.TYPE_BOOL:i=g!==1?d:this.xo(d);break;case this.TYPE_UINT8:i=g!==1?d:this.qb(d,1);break;case this.TYPE_UINT16:i=g!==2?d:this.qb(d,2);break;case this.TYPE_UINT32:i=g!==4?d:this.qb(d,4);break;case this.TYPE_UINT64:i=g!==8?d:this.qb(d,8);break;case this.TYPE_FLOAT:i=g!==4?d:this.qr(d);break;case this.TYPE_DOUBLE:i=g!==8?d:this.pr(d);break;case this.TYPE_STRING:i=this.Ui(d,!1);break;case this.TYPE_UNICODE_STRING:i=
g%2?d:this.Ui(d,!0);break;case this.TYPE_BINARY:i=d;break;case this.TYPE_COMPLEX:i=this.Jp(new f.ArrayReader(d),c);break;case this.TYPE_CUSTOM:i=a.Qb?a.Qb.call(this,d):i=d;break;default:i=[]}b[b.length]={gb:a,Y:i}}}return b},nt:function(e,c,b){var a=this,g=nokia.maps.util.Coroutine,c=g.create("nokia.maps.routing.nokia.TLVCodec.#readItemsAsyncCo",function(c){for(var i,j,h,m=null;(i=c.reader.read())!==-1;){if(i===0){c.record.push({gb:a.EOF,Y:null});b(c.record);return}i=a.Tl["".concat(c.aMessage," ",
i)];j=a.Kp(e,2);h=j>=0?a.Wm(c.reader,j):[];if(i){switch(i.u){case a.TYPE_VOID:break;case a.TYPE_BOOL:m=j!==1?h:a.xo(h);break;case a.TYPE_UINT8:m=j!==1?h:a.qb(h,1);break;case a.TYPE_UINT16:m=j!==2?h:a.qb(h,2);break;case a.TYPE_UINT32:m=j!==4?h:a.qb(h,4);break;case a.TYPE_UINT64:m=j!==8?h:a.qb(h,8);break;case a.TYPE_FLOAT:m=j!==4?h:a.qr(h);break;case a.TYPE_DOUBLE:m=j!==8?h:a.pr(h);break;case a.TYPE_STRING:m=a.Ui(h,!1);break;case a.TYPE_UNICODE_STRING:m=j%2?h:a.Ui(h,!0);break;case a.TYPE_BINARY:m=h;
break;case a.TYPE_COMPLEX:m=a.Jp(new f.ArrayReader(h),c.aMessage);break;case a.TYPE_CUSTOM:m=i.Qb?i.Qb.call(a,h):m=h;break;default:m=[]}c.record.push({gb:i,Y:m});if(++c.counter%c.decode_chunk_length===0)return g.yield()}}b(c.record)},"counter","reader","record","aMessage","decode_chunk_length")(0,e,[],c,500);c.run();return c},TYPE_VOID:0,TYPE_UINT8:1,TYPE_UINT16:2,TYPE_UINT32:4,TYPE_UINT64:8,TYPE_BOOL:9,TYPE_FLOAT:10,TYPE_DOUBLE:11,TYPE_STRING:12,TYPE_UNICODE_STRING:13,TYPE_BINARY:14,TYPE_COMPLEX:100,
TYPE_CUSTOM:200,MESSAGE_ALL:0,MESSAGE_REQUEST:1,MESSAGE_RESPONSE:2,Xr:{},Wr:{},Tl:{},uk:function(e){e=e*4294967296/360;return e-(e>2147483647?4294967296:0)},fj:function(e){return(e+(e<0?4294967296:0))*(360/4294967296)},Ho:function(e){return{latitude:this.fj(this.qb(e,4))-90,longitude:this.fj(this.qb(e.slice(4),4))-180}},Io:function(e,c){this.$c(e,4,this.uk(+c.latitude+90));this.$c(e,4,this.uk(+c.longitude+180))},ad:function(e){return{latitude:this.fj(this.qb(e.slice(4),4))-90,longitude:this.fj(this.qb(e,
4))-180}},Zg:function(e,c){this.$c(e,4,this.uk(+c.longitude+180));this.$c(e,4,this.uk(+c.latitude+90))}};(function(){function e(a){r=0;for(s=a.length;r<s;r++)(q=a[r])&&c(q[1],q[0],o,r)}function c(a,c,d,e){var h=new f.TLVTag;h.od=a;h.u=c;h.Du=d;h.d=e;b[a]=h;b.Tl["".concat(d," ",e)]=h}var b=f.TLVCodec,a=b.TYPE_VOID,g=b.TYPE_BOOL,d=b.TYPE_UINT8,i=b.TYPE_UINT16,j=b.TYPE_UINT32,h=b.TYPE_UINT64,m=b.TYPE_STRING,l=b.TYPE_UNICODE_STRING,k=b.TYPE_BINARY,n=b.TYPE_COMPLEX,p=b.TYPE_CUSTOM,o=b.MESSAGE_REQUEST,
q,r,s,w;for(w in b)b.hasOwnProperty(w)&&(w.match(/TYPE\_/)?b.Xr[b[w]]=w:w.match(/MESSAGE\_/)&&(b.Wr[b[w]]=w));c("EOF",b.TYPE_VOID,b.MESSAGE_ALL,0);e([0,[i,"ID_REQUEST_TYPE"],[l,"ID_REQUEST_LANGUAGE"],[j,"ID_REQUEST_NOANSWERS"],[g,"ID_REQUEST_BINARY"],[j,"ID_REQUEST_REPLY_LENGTH"],[g,"ID_REQUEST_EXCEED"],[l,"ID_REQUEST_DEVICE_ID"],[h,"ID_REQUEST_POSITION"],[l,"ID_REQUEST_ADDR_COUNTRY"],[l,"ID_REQUEST_ADDR_ZIP"],0,[l,"ID_REQUEST_ADDR_CITY"],[l,"ID_REQUEST_ADDR_STREET"],[l,"ID_REQUEST_ADDR_HOUSENUM"],
[l,"ID_REQUEST_ADDR_FREE_TEXT"],[l,"ID_REQUEST_OPERATOR"],0,0,0,[j,"ID_REQUEST_QUAD_TREE_DEPTH"],[l,"ID_REQUEST_QUAD_BLOCK_STRING"],[j,"ID_REQUEST_QUAD_BLOCK_NUMBER"],[j,"ID_REQUEST_VERSION_MAJOR"],[j,"ID_REQUEST_VERSION_MINOR"],[k,"ID_REQUEST_QUAD_LAYER_MASK"],[j,"ID_REQUEST_VERSION_FEATURE"],[j,"ID_REQUEST_VERSION_BUILD"],[j,"ID_REQUEST_QUAD_CACHEDAT_SELECT"],[g,"ID_REQUEST_ROUTE_AVOID_SEG"],[j,"ID_REQUEST_ROUTE_LEVEL"],[p,"ID_REQUEST_ROUTE_START_POSITION"],[p,"ID_REQUEST_ROUTE_END_POSITION"],[j,
"ID_REQUEST_ROUTE_START_SEGMENT"],[j,"ID_REQUEST_ROUTE_END_SEGMENT"],[j,"ID_REQUEST_ROUTE_FLAGS"],0,0,0,0,[p,"ID_REQUEST_POI_POSITION"],[j,"ID_REQUEST_POI_DISTANCE"],[l,"ID_REQUEST_POI_NAME"],[j,"ID_REQUEST_POI_CATEGORY"],[l,"ID_REQUEST_POI_LANGUAGE"],[h,"ID_REQUEST_POI_UL_CORNER"],[h,"ID_REQUEST_POI_LR_CORNER"],[j,"ID_REQUEST_POI_CAT_MASK"],[g,"ID_REQUEST_POI_ALL_CAT"],[j,"ID_REQUEST_OFFSET"],[g,"ID_REQUEST_POI_CATLOOKUP"],0,0,0,0,0,0,0,[j,"ID_REQUEST_TREE_ID"],[j,"ID_REQUEST_SUBVERSIONID"],[j,"ID_REQUEST_VERSION_KIND"],
[j,"ID_REQUEST_START_ID"],[l,"ID_REQUEST_INFORMATION_MODE"],[j,"ID_REQUEST_LEVELS"],[j,"ID_REQUEST_VERSIONID"],[l,"ID_REQUEST_PACKAGE_NAME"],[j,"ID_REQUEST_NODE_ID"],[j,"ID_REQUEST_PARENT_ID"],[l,"ID_REQUEST_PARAMETER"],[l,"ID_REQUEST_VALUE"],[l,"ID_REQUEST_ADDR_STATE"],[g,"ID_REQUEST_JUNCTION_INFO"],[j,"ID_REQUEST_CLIENT_VERSION_MAJOR"],[j,"ID_REQUEST_CLIENT_VERSION_MINOR"],[j,"ID_REQUEST_CLIENT_VERSION_FEATURE"],[j,"ID_REQUEST_CLIENT_VERSION_BUILD"],[l,"ID_REQUEST_UUID_IMSI"],[l,"ID_REQUEST_CLIENT_TYPE"],
[h,"ID_REQUEST_TIMESTAMP"],[j,"ID_REQUEST_TMCTOSTREET_TMCID"],[j,"ID_REQUEST_TMCTOSTREET_COUNTRYCODE"],[j,"ID_REQUEST_TMCTOSTREET_LTN"],[j,"ID_REQUEST_TMCTOSTREET_DIRECTION"],[j,"ID_REQUEST_TMCTOSTREET_EXTENT"],[h,"ID_LICENCE_ID"],[j,"ID_REQUEST_LATITUDE"],[j,"ID_REQUEST_LONGITUDE"],[j,"ID_REQUEST_ZOOMLEVEL"],[g,"ID_REQUEST_BASE64"],[g,"ID_REQUEST_ZLIB"],0,0,0,0,0,0,0,0,0,[g,"ID_REQUEST_UNICODE"],[j,"ID_REQUEST_DATA_VERSION_MAJOR"],[j,"ID_REQUEST_DATA_VERSION_MINOR"],[j,"ID_REQUEST_DATA_VERSION_FEATURE"],
[j,"ID_REQUEST_DATA_VERSION_BUILD"],[j,"ID_REQUEST_MAP_RADIUS"],[m,"ID_REQUEST_IMG_FORMAT"],[j,"ID_REQUEST_IMG_WIDTH"],[j,"ID_REQUEST_IMG_HEIGHT"],[g,"ID_REQUEST_IMG_NATIVE"],[k,"ID_TRAFFIC_MEASURE"],[j,"ID_REQUEST_MAP_SCHEME"],[k,"ID_DATA"],[k,"ID_ENCRYPTED_DATA_KEY_ID"],[k,"ID_ENCRYPTED_DATA_BLOB"],[k,"ID_ENCRYPTED_DATA_IV"],[k,"ID_REQUEST_ROUTE_AVOID_SEG_PENALTY"],[k,"ID_REQUEST_ROUTE_AVOID_SEG_DIRECTION"],[k,"ID_TRAFFIC_TESTCLIENT_ID"],[k,"ID_TRAFFIC_DATADICT"],[d,"ID_TRAFFIC_MEASURE_ENCODING"],
[l,"ID_REQUEST_ROUTE_GUIDANCE_LANGUAGE"],[k,"ID_REQUEST_IDLE_TIME"],[k,"ID_REQUEST_SAMPLING_INTERVAL"],[k,"ID_REQUEST_TILE_X"],[k,"ID_REQUEST_TILE_Y"],[k,"ID_REQUEST_TILE_Z"],[m,"ID_REQUEST_ADDR_DEVELOPER_KEY"],[m,"ID_REQUEST_ADDR_OUTPUT_FORMAT"],[g,"ID_REQUEST_LOOKAHEAD"],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,[g,"ID_REQUEST_MANEUVER_INFO"],0,0,0]);o=b.MESSAGE_RESPONSE;e([[a,"HL_END_OF_TRANSMISSION"],[j,"HL_ENTRIES"],[k,"HL_SEGMENTID"],[h,"HL_ZIPCODEID"],[h,"HL_DISTRICTID"],[j,"HL_CITYID"],
[p,"HL_POSITION"],[l,"HL_COUNTRYNAME"],[l,"HL_STREETNAME"],[l,"HL_ZIPCODENAME"],[l,"HL_DISTRICTNAME"],[l,"HL_CITYNAME"],[l,"HL_HOUSENUMBER"],[p,"HL_MINPOS"],[p,"HL_MAXPOS"],[d,"HL_AREATYPE"],[j,"HL_POPULATION"],[j,"HL_QUADBLOCK"],[j,"HL_CITYSCORE"],[j,"HL_CATEGORY"],[j,"HL_DISTANCE"],[l,"HL_NAME"],[m,"HL_PHONE"],[j,"HL_STREETCOUNT"],[l,"HL_ROUTENAME"],[j,"HL_POINTCOUNT"],[p,"HL_POINT"],[j,"HL_ATTRIBUTE"],[j,"HL_SIZE"],[k,"HL_DATE"],[j,"HL_OFFSET"],[j,"HL_OFFSET"],[l,"HL_PRE_NAME"],[l,"HL_POST_NAME"],
[j,"HL_URL_ID"],[j,"HL_PLACES_RATING"],[h,"HL_PLACES_TYPE"],[k,"HL_PLACES_ID"],0,0,[j,"HL_VERSION_RELEASE_MAJOR"],[j,"HL_VERSION_RELEASE_MINOR"],[j,"HL_VERSION_RELEASE_FEATURE"],[j,"HL_VERSION_RELEASE_BUILD"],[j,"HL_VERSION_RELEASE_DATE"],[j,"HL_VERSION_RELEASE_RECOMMENDATION"],[j,"HL_VERSION_RELEASE_STATUS"],[j,"HL_VERSION_RELEASE_COMMENT"],[j,"HL_VERSION_RELEASE_OUT_OF_SRV_DATE"],0,[j,"HL_VERSION_FILES_MAJOR"],[j,"HL_VERSION_FILES_MINOR"],[j,"HL_VERSION_FILES_FEATURE"],[j,"HL_VERSION_FILES_BUILD"],
[j,"HL_VERSION_FILES_DATE"],0,0,0,0,0,[j,"HL_VERSION_SERVER_MAJOR"],[j,"HL_VERSION_SERVER_MINOR"],[j,"HL_VERSION_SERVER_FEATURE"],[j,"HL_VERSION_SERVER_BUILD"],[j,"HL_VERSION_SERVER_DATE"],[j,"HL_VERSION_PROT_MAJOR"],[j,"HL_VERSION_PROT_MINOR"],[j,"HL_VERSION_PROT_FEATURE"],[j,"HL_VERSION_PROT_BUILD"],[h,"HL_NODE_ID"],[h,"HL_PARENT_ID"],[h,"HL_QUADBLOCK_COUNT"],[j,"HL_COUNT"],[h,"HL_BBOX1"],[h,"HL_BBOX2"],[h,"HL_CHILD_ID"],[h,"HL_LEAF"],0,[j,"HL_ICON_ID"],[l,"HL_LANGUAGE"],0,[g,"HL_UPDATE_AVAILABLE"],
[l,"HL_LINK"],[l,"HL_PROPERTY_NAME"],[l,"HL_PROPERTY_VALUE"],[l,"HL_MAILTO"],[n,"HL_JUNCTION_INFO"],[l,"HL_CATEGORY_NAME"],[k,"HL_BBOXS"],[k,"HL_VERSION_SUB_ID"],0,0,0,0,0,0,0,0,0,[k,"HL_TMC_DURATION"],[k,"HL_TMC_CONTROL_CODE"],[k,"HL_EVENT_ID"],[k,"HL_TMC_LOCATION_ID"],[k,"HL_TMC_DIRECTION"],[k,"HL_TMC_EXTENT"],[k,"HL_TMC_IID"],[k,"HL_TMC_GEOCOORDINATES"],[k,"HL_TMC_GDBIDS"],[k,"HL_TMC_AVOID"],[k,"HL_TMC_DIVERSION_ADVICE"],[k,"HL_TMC_SPEED_LIMIT"],[k,"HL_TMC_EXPLICIT_START_TIME"],[k,"HL_TMC_EXPLICIT_STOP_TIME"],
[k,"HL_TMC_SEPARATOR"],[m,"HL_TMC_CC"],0,[k,"HL_AVERAGE_SPEED"],[k,"HL_SPEED_LIMIT"],[k,"HL_FORM_OF_WAY"],[k,"HL_TMC_LOCATION_TABLE_NO"],[k,"HL_TMC_RDS_COUNTRY_CODE"],[k,"HL_TMC_LENGTH_ROUTE_AFFECTED"],[k,"HL_TMC_QUANTIFIER"],[k,"HL_TMC_SUPPL_INFO_CODE"],[k,"HL_TMC_ADDITIONAL_EVENT"],[k,"HL_TMC_DIVERSION_INSTRUCTIONS"],[k,"HL_TMC_DESTINATIONS"],[k,"HL_TMC_SOURCE_PROBLEM"],[k,"HL_TMC_START_TIMESTAMP"],[k,"HL_TMC_END_TIMESTAMP"],[l,"HL_ERROR_MSG"],[k,"HL_TMC_ACT_TIMESTAMP"],[k,"HL_TMC_EXP_TIMESTAMP"],
0,[j,"HL_ERROR_CODE"],[l,"HL_COUNTRYCODE"],[k,"HL_FUNCTIONAL_ROADCLASS"],[l,"HL_STATENAME"],[j,"HL_TZ_OFFSET_MINUTES"],0,[n,"HL_MAN_INFO"],[j,"HL_MAN_COUNT"],[d,"HL_MAN_ACTION_ID"],[d,"HL_MAN_TURN_ID"],[j,"HL_MAN_DISTANCE_FROM_START"],[l,"HL_MAN_NEXT_ROAD_NAME"],[d,"HL_MAN_TRAFFIC_DIRECTION"],[j,"HL_MAN_ANGLE"],[j,"HL_MAN_FLAGS"],[j,"HL_MAN_STARTSEGMENT_INDEX"],[j,"HL_MAN_ENDSEGMENT_INDEX"],[h,"HL_PT_SEGMENT_ID"],[j,"HL_PT_GEOMETRY_COUNT"],[j,"HL_PT_ATTRIBUTES"],[l,"HL_PT_DESTINATION"],[j,"HL_PT_LINE_GEOMETRY_COUNT"],
[l,"HL_PT_LINE_NAME"],[j,"HL_PT_FOREGROUND_COLOR"],[j,"HL_PT_BACKGROUND_COLOR"],[d,"HL_PT_LINE_STYLE"],[l,"HL_PT_OPERATOR_NAME"],[l,"HL_PT_OPERATOR_NAME_SHORT"],[k,"HL_PT_OPERATOR_LOGO"],[k,"HL_PT_OPERATOR_ICON"],[d,"HL_PT_TYPE"],[l,"HL_PT_TYPE_NAME"],[j,"HL_PT_DEPARTURE_TIME"],[j,"HL_PT_TIME_TO_ARRIVAL"],[n,"HL_PT_DEPARTURE_STOP"],[n,"HL_PT_ARRIVAL_STOP"],[j,"HL_PT_STOP_ATTRIBUTE"],[l,"HL_PT_STOP_NAME"],[l,"HL_PT_STOP_PLATFORM_NAME"],[p,"HL_PT_STOP_PLATFORM_LEVEL"],[p,"HL_PT_STOP_PLATFORM_COORDINATES"],
[p,"HL_PT_STOP_ENTRANCE_COORDINATES"],[l,"HL_MAN_NEXT_ROUTE_NAME"],[l,"HL_MAN_DIRECTIONS"],[l,"HL_MAN_EXIT_TEXT"],[j,"HL_DURATION"]]);c("HL_END_OF_RECORD",b.TYPE_VOID,o,254);b.ID_REQUEST_ROUTE_START_POSITION.Oc=b.Io;b.ID_REQUEST_ROUTE_START_POSITION.Qb=b.Ho;b.ID_REQUEST_ROUTE_END_POSITION.Oc=b.Io;b.ID_REQUEST_ROUTE_END_POSITION.Qb=b.Ho;b.ID_REQUEST_POI_POSITION.Oc=b.Zg;b.ID_REQUEST_POI_POSITION.Qb=b.ad;b.HL_POINT.Oc=b.Zg;b.HL_POINT.Qb=b.ad;b.HL_POSITION.Oc=b.Zg;b.HL_POSITION.Qb=b.ad;b.HL_MINPOS.Oc=
b.Zg;b.HL_MINPOS.Qb=b.ad;b.HL_MAXPOS.Oc=b.Zg;b.HL_MAXPOS.Qb=b.ad;b.HL_PT_STOP_PLATFORM_COORDINATES.Oc=b.ad;b.HL_PT_STOP_PLATFORM_COORDINATES.Qb=b.ad;b.HL_PT_STOP_ENTRANCE_COORDINATES.Oc=b.ad;b.HL_PT_STOP_ENTRANCE_COORDINATES.Qb=b.ad})()})(nokia.maps.routing.nokia);ovi.provide("nokia.maps.routing.nokia.RouteRequest");
(function(f){var e=nokia.maps,c=f.TLVCodec,b=f.HexWriter,a=e.net.Request,g=e.util.ApplicationContext;f.RouteRequest=new ovi.Class({initialize:function(b){this.Dc=b;this.Db=new a(a.JSONP,{callbackKey:"callback_func",autoSkip:!0});this.baseTlvUrl=b.get("routing.baseUrl")+b.get("routing.calculateroute.interface")+"?tlv="},requestRouteLeg:function(a,b,c,e){return this.Ct(this.jr(a,b,c),e)},cancel:function(a){this.Db.cancel(a)},Ct:function(a,b){a+=g.authenticationToken?"&token="+g.authenticationToken:
"";a+=g.appId?"&app_id="+g.appId:"";a+="&callback_id=0";return this.Db.send(a,b)},jr:function(a,e,f){var h;h=new b;a=this.Qr(a,e,this.Lr(f));c.yq(h,a);return this.baseTlvUrl+h.getContent()},Lr:function(a){return 0|a.routeType|a.routeMode|!a.allowHighways*4|!a.allowTunnels*8|!a.allowFerries*16|!a.allowTollRoads*32|!a.allowDirtRoads*8192|!a.allowRailFerries*16384},Qr:function(a,b,c){return[this.Sa("ID_REQUEST_CLIENT_VERSION_MAJOR",1),this.Sa("ID_REQUEST_CLIENT_VERSION_MINOR",4),this.Sa("ID_REQUEST_CLIENT_VERSION_FEATURE",
3),this.Sa("ID_REQUEST_VERSION_MINOR",this.Dc.get("routing.map_minor_version")),this.Sa("ID_REQUEST_VERSION_FEATURE",this.Dc.get("routing.map_feature_version")),this.Sa("ID_REQUEST_VERSION_BUILD",this.Dc.get("routing.map_build_version")),this.Sa("ID_REQUEST_TYPE",2),this.Sa("ID_REQUEST_UNICODE",!0),this.Sa("ID_REQUEST_ZLIB",!1),this.Sa("ID_REQUEST_BASE64",!1),this.Sa("ID_REQUEST_MANEUVER_INFO",!0),this.Sa("ID_REQUEST_JUNCTION_INFO",!0),this.Sa("ID_REQUEST_ROUTE_START_POSITION",a),this.Sa("ID_REQUEST_ROUTE_END_POSITION",
b),this.Sa("ID_REQUEST_ROUTE_FLAGS",c),this.Sa("ID_REQUEST_ROUTE_GUIDANCE_LANGUAGE","DEF")]},Sa:function(a,b){return{gb:c[a],Y:b}}})})(nokia.maps.routing.nokia);ovi.provide("nokia.maps.routing.nokia.RouteCreator");
(function(f){var e=nokia.maps,c=f.TLVCodec,b=f.Maneuver,a=Math.min,g=e.geo,d=g.Shape,i=f.RouteCreator=new ovi.Class({destroy:function(){this.$k&&e.util.Coroutine.kill(this.$k)},Statics:{STATUS_OK:0,STATUS_ERROR:1,STATUS_BUSY:2,STATUS_NOTRUN:3,STATUS_CANCELED:4,CAUSE_NO_ERROR:0,CAUSE_CANNOT_DO_PEDESTRIAN:1,CAUSE_GRAPH_DISCONNECTED:2,CAUSE_GRAPH_DISCONNECTED_CHECK_OPTIONS:3,CAUSE_NO_START_POINT:4,CAUSE_NO_END_POINT:5,CAUSE_NO_END_POINT_CHECK_OPTIONS:6,CAUSE_ROUTE_USES_DISABLED_ROADS:7},processRouteLeg:function(a,
b,c,d){if(a){var e=a.response&&a.response[1]||null;a.error?d({status:i.STATUS_CANCELED}):a.timeout?d({status:i.STATUS_ERROR,cause:e}):e?e.indexOf("<html")!==-1?d({status:i.STATUS_ERROR,cause:"server error"}):this.rr(e,b,c,d):d({status:i.STATUS_ERROR})}else d({status:i.STATUS_ERROR})},rr:function(d,e,m,l){var k=this,n=new f.HexReader(d),p=i;k.$k=c.nt(n,c.MESSAGE_RESPONSE,function(d){var f=d.length,j,s=0,w,u,v=null,x,z,E,G=[],L=[],F,B=[],K,y,A,O,N=/([^\s]*)? \/ (.*)/g,T=/^\D+\d+(\/\D+\d+)*$/g,M,H=g.Coordinate;
n=void 0;k.$k=null;if(!e.isCancelled)try{for(;s<f;s++)if(M=d[s],M.gb===c.HL_DURATION){e.travelTime=M.Y;break}for(;s<f;s++)if(M=d[s],M.gb===c.HL_STREETCOUNT){v=M.Y;break}for(w=v;w>0&&s<f;w--){for(E={name:"",points:[]};s<f;s++){M=d[s];if(M.gb===c.HL_END_OF_RECORD){s++;break}else if(M.gb===c.HL_STREETNAME)E.name=M.Y;M.gb===c.HL_POINT&&(E.points[E.points.length]={latitude:M.Y.latitude,longitude:M.Y.longitude})}G.push(E)}v>1&&(x=G[0],z=G[1],x.points.length>1&&z.points.length>0&&a(k.Tf(x.points[0],z.points[0]),
k.Tf(x.points[0],z.points[z.points.length-1]))<a(k.Tf(x.points[x.points.length-1],z.points[0]),k.Tf(x.points[x.points.length-1],z.points[z.points.length-1]))&&x.points.reverse());for(w=1;w<v;w++)x=G[w-1],z=G[w],x.points.length>0&&z.points.length>1&&k.Tf(x.points[x.points.length-1],z.points[0])>k.Tf(x.points[x.points.length-1],z.points[z.points.length-1])&&z.points.reverse();v>0&&(x=G[0],x.points.length>1&&k.Fp(x.points,e.start.originalPosition,m),x=G[G.length-1],x.points.length>1&&(x.points.reverse(),
k.Fp(x.points,e.end.originalPosition,m),x.points.reverse()));for(w=0;w<v;w++){x=G[w];u=0;for(w>0&&(u=1);u<x.points.length;u++)x.points[u].latitude&&x.points[u].longitude&&(L.push(x.points[u].latitude),L.push(x.points[u].longitude))}for(;!K&&s<f;s++)d[s].gb===c.HL_MAN_INFO&&(K=d[s]);j=K?K.Y.length:0;y=K?K.Y:[];u=0;for(w=y[u++].Y;w>0;w--){for(F=new b;u<j;u++){M=y[u];if(M.gb===c.HL_END_OF_RECORD){u++;break}switch(M.gb){case c.HL_MAN_ACTION_ID:F.action=M.Y;break;case c.HL_MAN_TURN_ID:F.turn=M.Y;break;
case c.HL_MAN_DISTANCE_FROM_START:F.distanceFromStart=M.Y;break;case c.HL_MAN_NEXT_ROAD_NAME:F.nextStreetName=M.Y;if(O=N.exec(F.nextStreetName))F.routeName=O[1],F.nextStreetName=O[2];else if(T.test(F.nextStreetName))F.routeName=F.nextStreetName;break;case c.HL_MAN_TRAFFIC_DIRECTION:F.trafficDirection=M.Y;break;case c.HL_MAN_ANGLE:F.angle=M.Y;break;case c.HL_MAN_DIRECTIONS:F.signPost=M.Y.split("|").join(" ");break;case c.HL_MAN_NEXT_ROUTE_NAME:F.routeName=M.Y;break;case c.HL_STREETNAME:F.streetName=
M.Y;break;case c.HL_MAN_STARTSEGMENT_INDEX:A=M.Y;E=G[A];F.streetName=F.streetName&&F.streetName.length>0?F.streetName:E.name;if(F.action===0||F.action===3)F.position=E.points.length>0?new H(E.points[0].latitude,E.points[0].longitude,void 0,!0):null;else{var D=E.points[E.points.length-1];F.position=new H(D.latitude,D.longitude,void 0,!0)}if(E.points.length>1){var S=E.points[E.points.length-2],C=E.points[E.points.length-1],sa=S.latitude*(Math.PI/180),I=C.latitude*(Math.PI/180),U=(C.longitude-S.longitude)*
(Math.PI/180);F.mapOrientation=(Math.atan2(Math.sin(U)*Math.cos(I),Math.cos(sa)*Math.sin(I)-Math.sin(sa)*Math.cos(I)*Math.cos(U))*(180/Math.PI)+360)%360}}}if(B.length>0)F.distanceFromPreviousManeuver=F.distanceFromStart-B[B.length-1].distanceFromStart,B[B.length-1].length=F.distanceFromPreviousManeuver,B[B.length-1].nextManeuver=F;B.push(F)}for(e.cause=p.CAUSE_NO_ERROR;s<f;s++)if(d[s].gb===c.HL_ERROR_CODE)e.cause=d[s].Y;e.points=L;if((e.maneuvers=B)&&B.length>0)e.length=B[B.length-1].distanceFromStart;
l({status:p.STATUS_OK,leg:e})}catch(X){ovi.error("RouteCreator._decodeResult: "+X.message),l({status:i.STATUS_ERROR})}})},Tf:function(a,b){return Math.abs(a.latitude-b.latitude)+Math.abs(a.longitude-b.longitude)},Fp:function(a,b,c){for(var b=c.geoToPoint(b),d=b.getNearest(c.geoToPoint(a[0]),c.geoToPoint(a[1])),e=d.distance(b),f=0,g,i,q=1,r=a.length-1;q<r;q++)g=b.getNearest(c.geoToPoint(a[q]),c.geoToPoint(a[q+1])),i=g.distance(b),i<e&&(e=i,d=g,f=q);a.splice(0,f);a[0]=c.pointToGeo(d)},create:function(a,
b,c,e,f){for(var b={duration:0,totalLength:0,waypoints:[],geometry:[],mode:e,legs:a,violations:{}},e=0,g=a.length;e<g;e++){this.Lq(b,a[e],e===0,e===a.length-1);var p=this.Tr(b,a[e],c,e);if(p!==i.CAUSE_NO_ERROR&&p!==i.CAUSE_GRAPH_DISCONNECTED_CHECK_OPTIONS)return f(null),!1}if(b)a=b.geometry,a.length>0&&d.fromLatLngArray(a,0,this.mr(b,f));return!0},mr:function(a,b){return function(c){a.shape=c;b(a)}},Lq:function(a,b,c,d){a.duration+=b.travelTime;a.totalLength+=b.length;if(b.points&&b.points.length>
0)a.geometry=a.geometry.concat(b.points);var e;if(b.maneuvers&&b.maneuvers.length>0){if(c)c=b.maneuvers[0],e=b.start,e.mappedPosition=c.position,c.waypoint=e,a.waypoints.push(b.start);c=b.maneuvers[b.maneuvers.length-1];e=b.end;e.mappedPosition=c.position;c.action=d?c.ACTION_END:c.ACTION_STOPOVER;c.waypoint=e;a.waypoints.push(b.end)}},Tr:function(a,b,c,d){var e=i.CAUSE_NO_ERROR,f=a.violations;if(e===i.CAUSE_NO_ERROR||e===i.CAUSE_GRAPH_DISCONNECTED_CHECK_OPTIONS){b.cause&16&&(e=d===0?i.CAUSE_NO_START_POINT:
i.CAUSE_GRAPH_DISCONNECTED);b.cause&32&&(e=d===a.legs.length-1?i.CAUSE_NO_END_POINT:i.CAUSE_GRAPH_DISCONNECTED);if(b.cause&64||b.cause&128)e=i.CAUSE_GRAPH_DISCONNECTED;if(b.cause&256)e=i.CAUSE_CANNOT_DO_PEDESTRIAN}if(e===i.CAUSE_NO_ERROR||e===i.CAUSE_GRAPH_DISCONNECTED_CHECK_OPTIONS){errorCount=0;if(b.cause&512&&!c.allowHighways)f.isAllowHighways=!0,errorCount++;if(b.cause&1024&&!c.allowTollRoads)f.isAllowTollRoads=!0,errorCount++;if(b.cause&2048&&!c.allowTunnels)f.isAllowTunnels=!0,errorCount++;
if(b.cause&4096&&!c.allowFerries)f.isAllowFerries=!0,errorCount++;if(b.cause&8192&&!c.allowDirtRoads)f.isAllowDirtRoads=!0,errorCount++;if(b.cause&16384&&!c.allowRailFerries)f.isAllowRailFerries=!0,errorCount++;if(errorCount)e=i.CAUSE_GRAPH_DISCONNECTED_CHECK_OPTIONS}return e}})})(nokia.maps.routing.nokia);ovi.provide("nokia.maps.routing.nokia.Manager");
(function(f){var e=f.routing,c=e.nokia,b=c.RouteCreator,a=c.RouteRequest,g=f.geo,d=g.Coordinate,i=c.Options,j=f.Config,h=c.Manager=new ovi.Class({Extends:e.Manager,initialize:function(a,b){this.set("state",h.State.INITIAL);this.routes=[];this.kh=[];this.routeCreator=void 0;this._super(a,b);if(!this.projection)this.projection=g.mercator},destroy:function(){this.routeCreator&&this.routeCreator.destroy&&this.routeCreator.destroy();this._super()},Statics:{State:{INITIAL:"initial",STARTED:"started",FINISHED:"finished",
CLEARED:"cleared",FAILED:"failed",CANCELLED:"cancelled",ROUTE_CALCULATED:"route calculated",ROUTE_FAILED:"route failed"}},Qm:0,calculateRoute:function(a,b){var c;(!(a instanceof nokia.maps.routing.WaypointParameterList)||ovi.type(b)!="array")&&f.util.f("the argument in calculateRoute Request is illegal");if(!(a.size()<2))this.get("state")===h.State.STARTED&&this.Wq(),this.clear(),this.kh=[],c=a.toCoordinates(),this.modes=b,this.Ps=this.ir(c),this.Xq(),this.Cc(c)},Tk:function(a){this.modes.splice(0,
1);this.modes.length!==0?(this.Qm=0,this.mj=!1,this.Cc(a)):this.set("state",h.State.FINISHED)},Cc:function(b){var c=b.length-1,d,e,f,g,j;for(this.set("state",h.State.STARTED,!0);c--&&this.get("state")===h.State.STARTED;)d=b[c],e=b[c+1],f=this.hr(d,e),this.kh[c]=f,g=new a(this.Dc),j=this.kr(f),i.setOptionsFromMode(this.modes[0]),d=g.requestRouteLeg(d,e,i.getOptions(),j),f.id=d,f.cancel=function(a,b){return function(){b.isCancelled=!0;a.cancel(this.id)}}(g,f)},kr:function(a){var b=this;return ovi.bind(b,
function(c){b.routeCreator.processRouteLeg(c,a,b.projection,b.Ps)})},ir:function(a){var c=this;return function(d){var e=++c.Qm===a.length-1;if(d.status===b.STATUS_OK&&e)c.routeCreator.create(c.kh,a,i.getOptions(),c.modes[0],c.lr(a));else if(d.status===b.STATUS_ERROR)c.mj?(c.modes=[],c.set("state",h.State.FAILED)):(c.set("state",h.State.ROUTE_FAILED),c.Tk(a))}},lr:function(a){var b=this;return function(c){c?(b.routes.push(c),b.set("state",h.State.ROUTE_CALCULATED),b.Tk(a)):b.mj?(b.modes=[],b.set("state",
h.State.FAILED)):(b.set("state",h.State.ROUTE_FAILED),b.Tk(a))}},hr:function(a,b){return{start:{originalPosition:new d(a.latitude,a.longitude,void 0,!0)},end:{originalPosition:new d(b.latitude,b.longitude,void 0,!0)}}},Wq:function(){this.modes=[];for(var a in this.kh)this.kh[a].cancel();this.set("state",h.State.CANCELLED,!0)},getRoutes:function(){return this.routes},getErrorCause:function(){return this.vu},clear:function(){this.routes=[];this.Qm=0},Xq:function(){this.mj=!0;if(this.modes.length===
3){var a=this.modes[0],b=this.modes[1];mode3=this.modes[2];if(a==="fastest"&&b==="shortest"&&mode3==="economic"&&a.disallowTollroads===b.disallowTollroads===mode3.disallowTollroads&&a.disallowMotorways===b.disallowMotorways===mode3.disallowMotorways&&a.disallowFerries===b.disallowFerries===mode3.disallowFerries&&a.disallowPublicTransport===b.disallowPublicTransport===mode3.disallowPublicTransport&&a.disallowTunnels===b.disallowTunnels===mode3.disallowTunnels&&a.disallowDirtRoads===b.disallowDirtRoads===
mode3.disallowDirtRoads)this.mj=!0}}}),m=new c.ioc.Injector(c.Context);delete c.Context;e.Manager.setDefImpl(function(){return m.get("manager")});j.setDefaultsNS("routing",{baseUrl:"https://web.archive.org/web/20170514173900/http://route.desktop.mos.svc.ovi.com/","calculateroute.interface":"rt",map_minor_version:2,map_feature_version:44,map_build_version:110},!0)})(nokia.maps);ovi.provide("nokia.maps.routing._packaging.package-nokia");})();


}
/*
     FILE ARCHIVED ON 17:39:00 May 14, 2017 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 12:21:48 Sep 19, 2022.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 225.893
  exclusion.robots: 0.087
  exclusion.robots.policy: 0.079
  RedisCDXSource: 82.599
  esindex: 0.017
  LoadShardBlock: 118.47 (3)
  PetaboxLoader3.datanode: 67.808 (5)
  CDXLines.iter: 20.105 (3)
  load_resource: 329.514 (2)
  PetaboxLoader3.resolve: 296.145 (2)
*/